version: '3'
services:
  app:
    build: .
    volumes:
        - ${PWD}:/code
        - /var/champions:/var/champions
    environment:
        PRODUCTION_CONFIG: /var/champions/config.py
    ports:
     - "80:80"
    depends_on:
     - database

  database:
    image: mariadb
    env_file:
        - /var/champions/database.env
    restart: on-failure
    ports:
        - "3306:3306"
    volumes:
        - /var/champions/mariadb:/var/lib/mysql
        - /var/champions:/var/champions


