version: '3'
services:
  app:
    build: .
    volumes:
        - ${PWD}:/code
    ports:
     - "80:80"
    depends_on:
     - database

  database:
    image: mariadb
    env_file:
        - ./production_database.env
    restart: on-failure
    ports:
        - "3306:3306"
    volumes:
        - /var/champions/mariadb:/var/lib/mysql


