version: '3'
services:
  app:
    build: .
    volumes:
        - ${PWD}:/code
    ports:
     - "80:80"
    depends_on:
     - database

  database:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: 'boot'
        MYSQL_DATABASE: "leagues"
        MYSQL_USER: "dummy"
        MYSQL_PASSWORD: "user"
    restart: on-failure
    volumes:
        - ${PWD}/mariadb:/var/lib/mysql


